# Set the custom display name of your keyboard when pairing over Bluetooth
CONFIG_ZMK_KEYBOARD_NAME="Crimtane"

# Use basic consumer usages for media keys to maximize compatibility with older OS/hardware
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

CONFIG_ZMK_SLEEP=y

CONFIG_ZMK_IDLE_TIMEOUT=60000

CONFIG_ZMK_SLEEP_TIMEOUT=900000

CONFIG_ZMK_PM_SOFT_OFF=y


