# Boost the Bluetooth transmission power to +8 dBm
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Set the custom display name of your keyboard when pairing over Bluetooth
CONFIG_ZMK_KEYBOARD_NAME="Crimtane"

# Use basic consumer usages for media keys to maximize compatibility with older OS/hardware
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y